SELECT t.INTAKE_ID, TASK_NUM, b.APP_PLATFORM AS PLATFORM, b.APP_PLATFORM || '/' || b.DATABASE_BASE_NAME  AS PLATFORM_NAME, t.DATABASE_BASE_ID as APP_ID, 
char  (date(t.SUBMIT_DATE),JIS) AS SUBMIT_DATE, SUBMITTER_BNS_ID,
u.FIRST_NAME || ' ' || u.LAST_NAME AS DBA_NAME, t.TASK_NAME, t.TASK_DESCRIPTION, t.WORK_EFFORT from long.task_tracking t
join long.user u  on u.BNS_ID = t.SUBMITTER_BNS_ID
join long.database_base b ON b.DATABASE_BASE_ID =  t.DATABASE_BASE_ID
where date(t.SUBMIT_DATE) >= '$START_DATE$' AND date(t.SUBMIT_DATE) <= DATE('$END_DATE$')