SELECT
CHANGE_ID,
ENV,
char  (date(CHANGE_START_TIME),JIS) || ' ' || char(time(CHANGE_START_TIME), JIS) AS CHANGE_START_TIME,
char  (date(CHANGE_END_TIME),JIS) || ' ' || char(time(CHANGE_END_TIME), JIS) AS CHANGE_END_TIME,
PRIORITY,
STATE,
OPENED_BY,
CONFIG_ITEM,
APPLICATION,
SHORT_DESC,
DESCRIPTION,
CIA,
CHANGE_PLAN,
VERIFICATION_PLAN,
COMMENT,
CREATE_TS,
UPDATE_TS
FROM long.SN_DB2_CHANGE
WHERE CHANGE_START_TIME between '$time_from$' AND '$time_end$'